source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MZPop_Example', :exclusive => true do
  pod 'MZPop', :path => '../'
end

target 'MZPop_Tests', :exclusive => true do
  pod 'MZPop', :path => '../'

  
end
