source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MZPop_Example' do
  pod 'MZPop', :path => '../'
  pod 'Masonry'
end

target 'MZPop_Tests' do
  pod 'MZPop', :path => '../'

  
end
